#include <iostream>

#ifndef CONSTANTES
#define CONSTANTES

#define MAX_JOGADORES 10
#define MAX_LETRAS 50
#define LARGURA_TELA 960
#define ALTURA_TELA 720
#define TAMANHO_BLOCO_LARGURA 64
#define TAMANHO_BLOCO_ALTURA 24
#define RAIO_BOLA 9
#define VELOCIDADE_BOLA_BASE 200.0f
#define VELOCIDADE_BARRA 420.0f
#define VIDAS_INICIAIS 3
#define MAX_BLOCOS 120
#define ARQUIVO_RANKING "ranking.txt"
#define MAX_FASES 3
#define MAPA_LINHAS 6
#define MAPA_COLUNAS 10
#define MAX_PARTICULAS 160
#define TEMPO_PARTICULA 0.45f
#define TAMANHO_ITEM 18

#define DIFICULDADE_FACIL 1
#define DIFICULDADE_MEDIO 2
#define DIFICULDADE_DIFICIL 3
#define FATOR_DIFICULDADE_FACIL 1.0f
#define FATOR_DIFICULDADE_MEDIO 1.25f
#define FATOR_DIFICULDADE_DIFICIL 1.5f

// Tipos de itens especiais
#define ITEM_VIDA 1
#define ITEM_AUMENTAR_BARRA 2
#define ITEM_DIMINUIR_BARRA 3
#define ITEM_PONTOS_EXTRAS 4
#define ITEM_INVERSOR 5
#define ITEM_ESCUDO 6

#define TEMPO_ESCUDO 8.0f

#define TIPO_BLOCO_CRISTAL 1
#define TIPO_BLOCO_CERAMICA 2
#define TIPO_BLOCO_OBSIDIANA 3
#define TIPO_BLOCO_METAL 4
#define TIPO_BLOCO_TITANIO 5

#define MAX_METEOROS 12
#define METEORO_INTERVALO_MIN 1.8f
#define METEORO_INTERVALO_MAX 4.0f

#endif
